### ISSUE TITLE
New tag please

### ISSUE THREAD

**Issue by Nyholm** [evert/google-api-php-client#13]
Hi.
Can you please make a new tag. I would like to use composer to install the library without dev stability

**Comment by evert** [comment]
This project is not maintained. Not putting it on dev stability would be a lie.

**Comment by Nyholm** [comment]
"Not maintained" is not the same as "not stable". There hasn't been any commits nor issues reported in months. That's pretty stable in my opinion.

**Comment by evert** [comment]
I started porting this project to using namespaces and I didn't even make it all the way through :S

**Comment by Nyholm** [comment]
It's just the test code that doesn't use namespaces... 

Since this update on packagist (https://groups.google.com/d/msg/composer-dev/_g3ASeIFlrc/Lu537ZXuOLgJ) I would prefer a tag on this repo.

**Comment by evert** [comment]
You can change the stability per dependency... What technical reason do you have for not doing that?

**Comment by Nyholm** [comment]
Sure you can. But it inconvenient to add "evert/google-api-php-client": "@dev" for a stable packet when it is one of your application's dependencies that depends on this packet. 

I don't have any pure technical reasons not to add that extra line in my composer.json. It's just simpler if stable packets are marked as stable.

**Comment by evert** [comment]
You do know that the google version 0.5.0 would also not be considered stable.. You still need that explicit dependency because it would be alpha..

**Comment by Nyholm** [comment]
Yes. But it is tagged with "0.5.0"..

**Comment by evert** [comment]
I mean, if your dependency relies on a 0.5.0 version of this package, your top-project still needs to explicitly require it too because 0.5.0 is also not stable..

So yea, I neither want to encourage anyone to use this package, nor cater to your OCD :) sorry dude

**Comment by Nyholm** [comment]
Thanks for replying. 

Have a nice day!
