### ISSUE TITLE
composer's basic demo cant be used

### ISSUE THREAD

**Issue by zairwolf** [evert/google-api-php-client#16]
Can anyone give me a demo? or give me the document. Now I dont know which should I use. "use \GoogleApi " seems not right.

**Comment by evert** [comment]
Hey zairwolf. This package was never completed, it doesn't work. Don't use it.

**Comment by zairwolf** [comment]
Google's document is messed up just as its API. sigh. Amazon is growing up

**Comment by zairwolf** [comment]
anyway, thanks evert.

**Comment by evert** [comment]
This is not an official package anyway =) Just an incomplete experiment. The reason I'm keeping it around is because for some reason, people started using it :(

**Comment by zairwolf** [comment]
hmmm.... In fact I cant find a detailed document about how to use the google drive via php. As I want to parse the shared url which user input and get the download link.

**Comment by evert** [comment]
Does this help?

https://developers.google.com/drive/web/quickstart/quickstart-php

**Comment by zairwolf** [comment]
Honestly, I dont know how to use it.
For example, I have a link to share: https://drive.google.com/file/d/0B9uylHGmqI37c3BLTV9lRkRGOEk/edit?usp=sharing
And I want to get the download url from it via PHP.
I used "https://www.googleapis.com/drive/v2/files/'.$fileID.'?key=MyKey" to parse it before. But this week it seems out of work. And I cant find any announcement from Google API. I guess maybe they stopped this API but without any explanation?

**Comment by evert** [comment]
Here's a specific example to download files with the SDK:

https://developers.google.com/drive/v2/reference/files/get

I can't help you much more than that though.

**Comment by zairwolf** [comment]
ic. I think I have know the way.
Thanks so much. have a good afternoon.
