### ISSUE TITLE
Merge with latest revision of the API

### ISSUE THREAD

**Issue by rvanlaak** [evert/google-api-php-client#5]
I noticed that there are differences between this fork and the API itself. For example, the Google Drive SDK has been updated to v2, which is a huge difference as you can see in: 
https://code.google.com/p/google-api-php-client/source/diff?spec=svn504&r=504&format=side&path=/trunk/src/contrib/Google_DriveService.php

Since I am planning on using the Drive API v2, can I help on merging with the latest version? 

Can you also please add the latest revision you forked to the readme?
https://code.google.com/p/google-api-php-client/source/list

**Comment by evert** [comment]
Hi!

I have to be honest with you, I have not done a ton of work on this project. If you want to try to bring it up to date with the latest version, by my guest. I'm not doing a ton of maintenance here though..

Evert

**Comment by rvanlaak** [comment]
Besides that; I noticed you're also active in a similar Packagist package:

https://packagist.org/packages/dag/google-api-php-client

Is that version newer? Can you advise me on the version to work on?

**Comment by evert** [comment]
I think that was originally a fork. The author was kind to keep my name in it.. Ask him, i'd be curious what the status is.

**Comment by rvanlaak** [comment]
I've investigated the Google library a bit more, revision474 did the work for us I think! From that moment and onward it is possible to use prefixing/namespaces.
http://code.google.com/p/google-api-php-client/source/detail?r=474

For Symfony2 users, make use of the classloader prefixing, as described on http://symfony.com/doc/current/components/class_loader.html

My question for this moment: does this make your library obsolete?

**Comment by evert** [comment]
Perhaps. I started this project because I needed this API to be modernized a bit, but before I got to use it.. the actual project I needed it for got postponed.

So, I have never use this library.. like ever. I kept it for the few people that have used it. You'll need to do your own research.
